version: 2.1
orbs:
  golang-ci: financial-times/golang-ci@1.0.0

workflows:
  tests_and_docker:
    jobs:
      - golang-ci/build-and-test:
          name: build-and-test-project

      - golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project

  scanning:
    jobs:
      - golang-ci/scan:
          name: scan-dependencies
          context: org-global