# Default values for resilient-splunk-forwarder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/resilient-splunk-forwarder
  version: "" # should be set explicitly at installation
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 256Mi
  requests:
    memory: 50Mi
env:
  WORKERS: "20"
  CHAN_BUFFER: "256"
metrics:
  # where we expose the metrics for prometheus
  path: /metrics
  # how often prometheus will call the metrics path
  interval: 15s
  # the name of the prometheus instance, as defined in
  # content-k8s-prometheus\helm\content-k8s-prometheus\app-configs\monitoring-metrics_{env}.yaml
  prometheusInstance: monitoring-metrics
