apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: WORKERS
          value: "{{ .Values.env.WORKERS }}"
        - name: CHAN_BUFFER
          value: "{{ .Values.env.CHAN_BUFFER }}"
        - name: GRAPHITE_SERVER
          value: "{{ .Values.env.GRAPHITE_SERVER }}"
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk.forwarder.s3.bucket
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk.forwarder.aws.region
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: environment
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: splunk-forwarder
              key: aws.access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: splunk-forwarder
              key: aws.secret_access_key
        - name: FORWARD_URL
          valueFrom:
            secretKeyRef:
              name: splunk-forwarder
              key: hec.url
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-forwarder
              key: hec.token
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}

