apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: splunk-forwarder
  namespace: default
  type: Opaque
spec:
  encryptedData:
{{ if .Values.encrypted-secrets }}{{ toYaml .Values.encrypted-secrets | indent 4 }}{{ end }}
