apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: splunk-forwarder
  namespace: default
  type: Opaque
spec:
  encryptedData:
{{ if .Values.encryptedsecrets }}{{ toYaml .Values.encryptedsecrets | indent 4 }}{{ end }}
